---
name: CI
'on': [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Instala Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Start Appium Server
        run: |
            nohup appium > appium.log 2>&1 &
            sleep 10 

      - name: Download Android SDK tools
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel
          script: |
            adb devices
            adb install android.wdio.native.app.v1.0.8.apk
            npm test

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: logs
          path: logs
